some change

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -274,17 +274,17 @@ parts:
         /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/graphviz/config* \
         ${SNAPCRAFT_PART_INSTALL}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/graphviz/
 
-  cleanup:
-    after: [stub-chown, freecad, python-packages, snap-setup-mod, graphviz]
-    plugin: nil
-    build-snaps: [kde-frameworks-5-91-qt-5-15-3-core20]
-    override-prime: |
-      set -eux
-      for snap in "kde-frameworks-5-91-qt-5-15-3-core20"; do  # List all content-snaps you're using here
-        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
-      done
-      for cruft in bug lintian man; do
-        rm -rf $SNAPCRAFT_PRIME/usr/share/$cruft
-      done
-      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
-      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
+  # cleanup:
+  #   after: [stub-chown, freecad, python-packages, snap-setup-mod, graphviz]
+  #   plugin: nil
+  #   build-snaps: [kde-frameworks-5-91-qt-5-15-3-core20]
+  #   override-prime: |
+  #     set -eux
+  #     for snap in "kde-frameworks-5-91-qt-5-15-3-core20"; do  # List all content-snaps you're using here
+  #       cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
+  #     done
+  #     for cruft in bug lintian man; do
+  #       rm -rf $SNAPCRAFT_PRIME/usr/share/$cruft
+  #     done
+  #     find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
+  #     find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
